name: strobealign
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-genome-download
  # - mason=2.0.9 # we compile a more recent version to avoid some crashes
    # Snakemake >=9.10.0 sometimes runs too many jobs in parallel, skewing our
    # runtime measurements (see
    # https://github.com/snakemake/snakemake/issues/3913)
  - snakemake-minimal=9.9.0
  - snakemake-executor-plugin-slurm
  - python=3.13
  - pysam=0.23
  - dnaio
  - bwa=0.7.19
  - x-mapper=1.2.0
  - samtools=1.22
  - cmake=4.2
  - cxx-compiler=1.11.0
  - zlib
  - seaborn=0.13.2
  - minimap2=2.30
  - isa-l
  - pyyaml
  - pyfaidx=0.9.0.3
  - pbsim3=3.0.5
  - pbccs=6.4.0
  - biopython=1.86
