name: strobealign
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-genome-download
  # - mason=2.0.9 # we compile a more recent version to avoid some crashes
    # More recent snakemake versions cannot be used with SLURM due to https://github.com/snakemake/snakemake/issues/3853
  - snakemake-minimal=9.13.7
  - snakemake-executor-plugin-slurm
  - python=3.13
  - pysam=0.23
  - dnaio
  - bwa=0.7.19
  - samtools=1.22
  - cmake=4.2
  - cxx-compiler
  - seaborn
  - minimap2=2.30
  - isa-l
  - pyyaml
  - pyfaidx
