name: strobealign-eval
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-genome-download
  # - mason=2.0.9 # we compile a more recent version to avoid some crashes
  - snakemake-minimal=9
  - python=3.13
  - pysam=0.23
  - dnaio
  - bwa=0.7.19
  - samtools=1.22
  - cmake=4.2
  - cxx-compiler
  - seaborn
  - minimap2=2.30
  - isa-l
  - pyyaml
  - pyfaidx
