# Example evaluation configuration with most datasets and libraries enabled

# Uncomment and change to use commits from a different repository
# repository: "https://github.com/ksahlin/strobealign.git"

mode:
  - map
  - align

ends:
  - se
  - pe

datasets:
  - sim0
  - sim3
  - sim4
  - sim5
  - sim6

genomes:
  - fruitfly
  - maize
  - CHM13
  - rye
#  - chrY

read-lengths:
  - 50
  - 75
  - 100
  - 150
  - 200
  - 300
  - 500
  - 1000
  - 5000
  - 10000

# Programs to run in addition to strobealign
programs:
 - bwamem
 - minimap2
 - xmapper

# Strobealign commits
# For color names, see https://matplotlib.org/stable/gallery/color/named_colors.html
versions:
  - commit: "v0.14.0"
    color: "yellow"
    name: "strobealign 0.14.0"  # used as plot legend

  - commit: "v0.15.0"
    color: "cyan"
    name: "strobealign 0.15.0"
 
  - commit: "v0.16.0"
    color: "green"
    name: "strobealign 0.16.0"
 
# To Do fix this
# Rust version is recognized by a rs- prefix in the key
#  - commit: "f2107853"
#    color: "purple"
#    name: "strobealign-rs 0.16"
