modes:
  - map
  - align

ends:
  - se
  - pe

datasets:
  - sim0
  - sim4
  - sim6

genomes:
  - fruitfly
  - maize
  - CHM13
  - rye
#  - chrY

read-lengths:
  - 50
  - 75
  - 100
  - 150
  - 200
  - 300
  - 500
  - 1000
  - 5000
  - 10000

# Programs to run in addition to strobealign
programs:
 - bwamem
 - minimap2
# - xmapper

# For color names, see https://matplotlib.org/stable/gallery/color/named_colors.html
# tab:green
# plum
# navy
# brown
# black
# cyan
# red

versions:
  - commit: "caa3745f"
    name: "strobealign 0.17.0 mcs=always"
    color: "tab:green"

  - commit: "caa3745f"
    name: "strobealign 0.17.0 mcs=off"
    arguments: "--mcs=off"
    color: "grey"

  - commit: "caa3745f"
    name: "strobealign 0.17.0 mcs=rescue"
    arguments: "--mcs=rescue"
    color: "plum"

  - commit: "caa3745f"
    name: "strobealign 0.17.0 mcs=first-strobe"
    arguments: "--mcs=first-strobe"
    color: "lightgreen"

  - commit: "caa3745f"
    name: "strobealign 0.17.0 noisy"
    arguments: "-k 16 -s 12 -l 2 -u 2"
    color: "red"
